### ISSUE TITLE
Support for arbitrary CPUs

### ISSUE THREAD

**Issue by nstbayless** [leiradel/hackable-console#2]
## Suggestion

Currently, `hcdebug.h` contains a list of defines specifically for the 6502 and z80. Instead, why not allow the core to specify the CPU's number and names of its registers and interrupts? The core could also provide a function to (dis)assemble instructions for the CPU and any other CPU-specific functionality the front-end needs. This would allow the front-end to be more flexible to support different types of cores, and it would mean support could be added for new cores without requiring the front-end to be modified.

**Comment by leiradel** [comment]
That was the original plan, the `hc_Cpu` structure used to have an array of `hc_Register` for the debugger to use. However, I wanted to show things like a mini 48-bytes hex editor for memory pointed to by registers like `HL`, a mini stack view for `SP`, and I wanted to show if a branch would be taken or not in the disassembly view depending on the flags in `F`, as well as memory contents for instructions that access memory.

I started implementing that by tagging registers in the `hc_Register` array with things like `HC_REG_MEMORY_POINTER` and `HC_REG_STACK_POINTER`, but it was getting way to complicated and still didn't work for things like the disassembly view.

So I decided to let the debugger know all about the CPUs and their registers, so that it's possible to have really all that extended information without the complications of trying to be generic. This also saves core maintainers from having to implement a disassembler. If the debugger lacks a disassembler for a given CPU, it can be contributed in a PR instead of added directly to the core.

Does that make sense?

**Comment by nstbayless** [comment]
That does make sense, and I can see how it could get complicated. However, the current approach makes it harder for people to help extend this project by e.g. implementing the functionality in more cores. Ideally, to add debugging support to a new core, it should only take an update to one repo (the core) and not two. I was actually thinking of implementing this in a snes debugger today (or at least giving it a shot) and then maybe some other cores too, but having to edit two code bases simultaneously is a bit scary.

Maybe this is a sign that more work should be done inside the core rather than in the front-end. For example, instead of `HC_REG_STACK_POINTER`, you could have a callback in the CPU like `get_stack_info` which returns this struct:

```c++
typedef struct {
  int stack_grows_upward; // if 0, then grows downward (toward zero); if 1, stack grows upward (toward positive addresses)
  uint64_t stack_begin;
  uint64_t stack_pointer; // if stack grows upward, this points to where the next byte would be added; if stack grows downward, this points to that value plus one.
  uint64_t stack_size; // the maximum possible size the stack can be. (if UINT64_MAX then the stack is effectively unbounded,)
} hc_StackInfo;
```

In general, you could take a fully agnostic view of what the stack register semantics are and treat them as completely arbitrary values with a name. The core can provide information in other ways. For example, CPU flags (like 6502's Z, N, C, V, etc) can be represented entirely without acknowledging the meaning of the cpu status register `SR` (which stores those flags) via an array like so:

```c++
typedef struct {
  char const* name;
  int (*get)(); // returns 0 or 1 if enabled or disabled
  void (*set)(int yes); // sets the flag to enabled or disabled (0 or 1)
} hc_StatusFlag;
```

Behind the scenes, the core can implement `get` and `set` by reading/editing the `SR` register, but the front-end doesn't need to know that this is what the SR register is for. Similarly, the front-end doesn't need to know that the stack pointer `S` is the source-of-truth for `hc_StackInfo`. Furthermore, all of these features could be totally optional (at the cost of restricted functionality), so that it's easier to get the ball rolling on implementing `hcdebug.h` in a new console.

I imagine there is a similar solution for the memory-pointer registers in Z80, which I'm not familiar with. If there is truly something that is very CPU-specific, then perhaps that could be handled as a special case, or else `hcdebug.h` could include some lower-level API for allowing the core to provide its own custom debug widgets (which might be a good idea down the line anyway, since different cores have vastly different peripherals, like the NES' and SNES' array of mmc units and sound chips); perhaps simply exposing DearImgui to the core is almost enough.

Regarding disassembly: what if the architecture or bytecode language is too specific to be accepted as a PR? If somebody is implementing a new core from scratch for something that doesn't resemble a common retro console, then it might be too specific to that project to warrant support upstream in hackable-console. In any case, it would be easier for the developer if they didn't have to wait for their PR to be approved before they can rely on an unmodified hackable-console to be able to debug their core.

A hybrid approach might be a good idea here: the core can select from a number of disassemblers already implemented in hackable-console (like Z80, 6502, x86, etc.) or else provide its own.

**Comment by leiradel** [comment]
> However, the current approach makes it harder for people to help extend this project by e.g. implementing the functionality in more cores.

I think it's the opposite, if the frontend knows how to disassemble instructions and how to show the CPU state, the core has less things to worry with.

> I was actually thinking of implementing this in a snes debugger today (or at least giving it a shot) and then maybe some other cores too, but having to edit two code bases simultaneously is a bit scary.

Maybe it is for the first contributor to a new CPU, but then for other developers it's just a matter of declaring the correct CPU type and everything will just work. If these have to be implemented in the cores, I can see some people not doing it because the amount of things to write to be able to debug the core will be much greater.

> you could have a callback in the CPU like get_stack_info which returns this struct:

Yes, but it gets increasingly complicated. Besides, like I said I want to have the disassembler in the frontend side to 1) avoid core maintainers from implementing one for each core, and 2) make sure I can have perks like I listed in the previous comment. Since I already need to know what CPU I'm dealing with in the frontend, it's easier if the cores just inform which CPU they have and let the frontend deal with everything.

> I imagine there is a similar solution for the memory-pointer registers in Z80, which I'm not familiar with.

It's not really something unique to the Z80, but when disassembling the instruction `LD A, (IX+0x40)` I want to show the value of the byte at that memory address, which needs both knowledge of the instructions and registers. At the right of that instruction I want to have a button that will open a memory view with the address already selected, so the disassembly needs to call into UI functions.

> perhaps simply exposing DearImgui to the core is almost enough.

Maybe, but it gets increasingly difficult to change the core to work with the debugger, not counting writing a frontend with a different GUI framework.

> what if the architecture or bytecode language is too specific to be accepted as a PR?

That is 100% fine and will be accepted, as long as the required functionality (disassembly and CPU state view) is isolated in their own files.

> In any case, it would be easier for the developer if they didn't have to wait for their PR to be approved

Well that's the nature of open source projects. The developer would have their own fork to be able to add what they need anyway, so they can work with their fork until the PR is merged.

**Comment by nstbayless** [comment]
Alright, I can agree with this philosophy. Still, it might make sense to provide the core with the at least the option of implementing many of these things core-side if they aren't implemented in the front-end.

I'll mark the issue as closed.
