### ISSUE TITLE
Missing autorun.lua

### ISSUE THREAD

**Issue by nstbayless** [leiradel/hackable-console#3]
After building hackable-console on Linux Mint 20, I get the following error when running `hackcon`:

```
[NFO] [CFG] The scripts path is "~/.hackable-console/scripts/"
[NFO] [CFG] The system path is "~/.hackable-console/system/"
[NFO] [CFG] The core assets path is "~/.hackable-console/assets/"
[NFO] [CFG] The save path is "~/.hackable-console/saves/"
[NFO] [CFG] The cores path is "~/.hackable-console/cores/"
[NFO] [HC ] Running "~/.hackable-console/scripts/autorun.lua"
[ERR] [LUA] cannot open ~/.hackable-console/scripts/autorun.lua: No such file or directory
stack traceback:
        [C]: in ?
```

I've confirmed that `~/.hackable-console/scripts` is a directory which exists, but it is empty. Copying the contents of `etc/scripts` to `~/.hackable-console/scripts` resolves the issue.

**Comment by leiradel** [comment]
Sorry about that, `hackcon` looks for Lua scripts when booting in `~/.hackable-console/scripts/`. You'll find the `autorun.lua` script in `etc/scripts`, as well as scripts that load and configure some Libretro cores so that their memory is exposed to the frontend.

I'll close the issue but feel free to re-open it if you have other issues with the scripts.

**Comment by nstbayless** [comment]
Ok. It might make sense to have hackcon automatically populate the scripts folder with autorun.lua in its own.

**Comment by leiradel** [comment]
That's a good idea.
